# Generated by Django 6.0.2 on 2026-03-08 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='sets',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_sets', models.IntegerField(default=3)),
                ('target_reps', models.IntegerField(default=10)),
                ('order', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.exerciselibrary')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='core.workoutprogram')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
