# Generated by Django 6.0.2 on 2026-03-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workoutlog_sets_workoutprogram_programexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='day_of_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
