# Generated by Django 6.0.2 on 2026-03-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workoutprogram_day_of_week_alter_workoutprogram_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='programexercise',
            name='target_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
